id: I11E103B2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T00:41:24+00:00'
last_modified: '2022-06-08T16:03:48.026628+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3680
  title: དྭགས་པོ་ཐར་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AF30:
      image_group_id: I1KG3732
      title: ''
      total_pages: 324
      order: 1
      base_file: AF30.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
