id: P010580
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3680
  title: དྭགས་པོ་ཐར་རྒྱན
  author: ''
  volumes:
    8f4ee3ad7beb4fa9a12a555b431974f5:
      image_group_id: I1KG3732
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
